//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShomaRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AcutraqScrenning
    {
        public long Id { get; set; }
        public Nullable<int> TenantId { get; set; }
        public string ServiceCode { get; set; }
        public string OrderCode { get; set; }
        public string CAOrderCode { get; set; }
        public string Status { get; set; }
        public byte[] Message { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    }
}
