//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShomaRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Visit
    {
        public long VisitID { get; set; }
        public Nullable<long> ProspectID { get; set; }
        public Nullable<int> VisitNumber { get; set; }
        public Nullable<System.DateTime> VisitDateTime { get; set; }
        public string ResultCode { get; set; }
        public string Details { get; set; }
        public Nullable<int> Activity { get; set; }
        public Nullable<int> VisitIncharge { get; set; }
        public Nullable<int> VisitSlot { get; set; }
    
        public virtual tbl_Prospect tbl_Prospect { get; set; }
    }
}
