//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShomaRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AuditHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_AuditHistory()
        {
            this.tbl_AuditHistoryDetail = new HashSet<tbl_AuditHistoryDetail>();
        }
    
        public int AHID { get; set; }
        public string TableName { get; set; }
        public string EventName { get; set; }
        public int EventRows { get; set; }
        public System.DateTime EventDate { get; set; }
        public string UserName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AuditHistoryDetail> tbl_AuditHistoryDetail { get; set; }
    }
}
