//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShomaRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BankAccount
    {
        public int BAID { get; set; }
        public string Bank_Name { get; set; }
        public string Account_Number { get; set; }
        public Nullable<int> Account_Type { get; set; }
    }
}
