//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShomaRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Lease
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Lease()
        {
            this.tbl_CashReceipts = new HashSet<tbl_CashReceipts>();
            this.tbl_LeaseRenewal = new HashSet<tbl_LeaseRenewal>();
            this.tbl_LeaseTransfer = new HashSet<tbl_LeaseTransfer>();
            this.tbl_Notice = new HashSet<tbl_Notice>();
            this.tbl_UtilityBilling = new HashSet<tbl_UtilityBilling>();
        }
    
        public long LID { get; set; }
        public Nullable<long> PID { get; set; }
        public Nullable<long> UID { get; set; }
        public long TenantID { get; set; }
        public Nullable<int> Revision_Num { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Being_Terminated { get; set; }
        public string Phase { get; set; }
        public Nullable<System.DateTime> Notice_Date { get; set; }
        public string Termination_Reason { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> Previous_Balance { get; set; }
        public Nullable<int> Returned_Check_Limit { get; set; }
        public Nullable<int> Number_Returned_Checks { get; set; }
        public Nullable<System.DateTime> Last_Return_Ck_Date { get; set; }
        public Nullable<int> Last_Return_Pmt_ID { get; set; }
        public Nullable<int> Last_Return_Ck_Num { get; set; }
        public Nullable<System.DateTime> Original_Start { get; set; }
        public Nullable<System.DateTime> Actual_Start { get; set; }
        public Nullable<System.DateTime> Original_Lease_End { get; set; }
        public Nullable<System.DateTime> Actual_Lease_End { get; set; }
        public Nullable<System.DateTime> Intended_MoveIn_Date { get; set; }
        public Nullable<System.DateTime> Actual_MoveIn_Date { get; set; }
        public Nullable<System.DateTime> Intend_MoveOut_Date { get; set; }
        public Nullable<System.DateTime> Actual_MoveOut_Date { get; set; }
        public string Statement_Type { get; set; }
        public Nullable<System.DateTime> Last_Rent_Roll_Date { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> Reconciled { get; set; }
        public string Term { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CashReceipts> tbl_CashReceipts { get; set; }
        public virtual tbl_Login tbl_Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LeaseRenewal> tbl_LeaseRenewal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LeaseTransfer> tbl_LeaseTransfer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Notice> tbl_Notice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UtilityBilling> tbl_UtilityBilling { get; set; }
        public virtual tbl_Properties tbl_Properties { get; set; }
    }
}
