//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShomaRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AuditHistoryDetail
    {
        public int AHDID { get; set; }
        public int AHID { get; set; }
        public string PKColumnValue { get; set; }
        public string FKColumnValue { get; set; }
        public string AuditDetails { get; set; }
    
        public virtual tbl_AuditHistory tbl_AuditHistory { get; set; }
    }
}
