//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShomaRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LeaseTransfer
    {
        public long LID { get; set; }
        public int Revision_Num { get; set; }
        public Nullable<System.DateTime> LeaseStart { get; set; }
        public Nullable<System.DateTime> LeaseEnd { get; set; }
        public string UnitFrom { get; set; }
        public string UnitTo { get; set; }
        public Nullable<System.DateTime> MoveIn { get; set; }
        public long ID { get; set; }
    
        public virtual tbl_Lease tbl_Lease { get; set; }
    }
}
