//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShomaRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Gallery
    {
        public long GID { get; set; }
        public string PhotoPath { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
        public Nullable<long> PID { get; set; }
        public string ToolTip { get; set; }
    
        public virtual tbl_Properties tbl_Properties { get; set; }
    }
}
