//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShomaRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ESignPolicyAgreement
    {
        public long ESPAID { get; set; }
        public Nullable<long> TenantID { get; set; }
        public Nullable<long> ApplicantID { get; set; }
        public string Key { get; set; }
        public string EsignatureId { get; set; }
        public string DateSigned { get; set; }
        public Nullable<long> LeaseID { get; set; }
        public string Type { get; set; }
        public Nullable<int> IsAgreementOrPolicy { get; set; }
        public Nullable<long> UserID { get; set; }
    }
}
