//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShomaRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TenantPet
    {
        public int PetID { get; set; }
        public Nullable<long> TenantID { get; set; }
        public Nullable<int> PetType { get; set; }
        public string Breed { get; set; }
        public string Weight { get; set; }
        public string Age { get; set; }
        public string Photo { get; set; }
        public string PetVaccinationCert { get; set; }
        public string PetName { get; set; }
        public string VetsName { get; set; }
        public string OriginalPhoto { get; set; }
        public string OriginalVaccinationCert { get; set; }
        public string UniqID { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    
        public virtual tbl_ApplyNow tbl_ApplyNow { get; set; }
    }
}
