//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShomaRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmployerHistory
    {
        public long HEIID { get; set; }
        public string EmployerName { get; set; }
        public string JobTitle { get; set; }
        public Nullable<int> JobType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public Nullable<decimal> AnnualIncome { get; set; }
        public Nullable<decimal> AddAnnualIncome { get; set; }
        public string SupervisorName { get; set; }
        public string SupervisorPhone { get; set; }
        public string SupervisorEmail { get; set; }
        public Nullable<int> Country { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public Nullable<int> State { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public string TaxReturn1 { get; set; }
        public string TaxReturn2 { get; set; }
        public string TaxReturn3 { get; set; }
        public string TaxReturn1OrigName { get; set; }
        public string TaxReturn2OrigName { get; set; }
        public string TaxReturn3OrigName { get; set; }
        public Nullable<int> PaystubValue { get; set; }
        public Nullable<long> TenantId { get; set; }
        public string TerminationReason { get; set; }
    }
}
