//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShomaRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Bill
    {
        public long BillID { get; set; }
        public long TransID { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
