//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShomaRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Club
    {
        public long Id { get; set; }
        public string ClubTitle { get; set; }
        public long ActivityId { get; set; }
        public System.DateTime StartDate { get; set; }
        public string Venue { get; set; }
        public long DayId { get; set; }
        public string Time { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneCheck { get; set; }
        public bool EmailCheck { get; set; }
        public long LevelId { get; set; }
        public string SpecialInstruction { get; set; }
        public string Description { get; set; }
        public string BriefDescription { get; set; }
        public bool TermsAndCondition { get; set; }
        public Nullable<long> TenantID { get; set; }
        public long UserId { get; set; }
        public bool IsDeleted { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    }
}
