//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShomaRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LeaseRenewal
    {
        public long LID { get; set; }
        public Nullable<int> Revision_Num { get; set; }
        public Nullable<System.DateTime> RenewalDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> PriorLeaseBegin { get; set; }
        public Nullable<System.DateTime> PriorLeaseEnd { get; set; }
        public long ID { get; set; }
    
        public virtual tbl_Lease tbl_Lease { get; set; }
    }
}
