//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShomaRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SMSMessages
    {
        public long MsgID { get; set; }
        public string PhoneNumber { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
    }
}
