//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShomaRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FacilityBooking
    {
        public long FacilityBookingID { get; set; }
        public Nullable<long> TenantID { get; set; }
        public Nullable<int> FacilityID { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public string BookingDetails { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> RequiredFromDate { get; set; }
        public Nullable<System.DateTime> RequiredToDate { get; set; }
    
        public virtual tbl_Facility tbl_Facility { get; set; }
        public virtual tbl_Tenant tbl_Tenant { get; set; }
        public virtual tbl_Login tbl_Login { get; set; }
    }
}
