//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShomaRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UtilityBilling
    {
        public long UBID { get; set; }
        public Nullable<int> UtilityID { get; set; }
        public Nullable<long> LeaseID { get; set; }
        public Nullable<int> Revision_Num { get; set; }
        public string Unit { get; set; }
        public string ChargeType { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<decimal> MeterReading { get; set; }
        public Nullable<decimal> PricePerUnit { get; set; }
        public Nullable<System.DateTime> Posted { get; set; }
        public long TenantID { get; set; }
    
        public virtual tbl_Tenant tbl_Tenant { get; set; }
        public virtual tbl_Utility tbl_Utility { get; set; }
        public virtual tbl_Lease tbl_Lease { get; set; }
    }
}
