//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShomaRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_WorkOrder
    {
        public long WOID { get; set; }
        public Nullable<long> TenantID { get; set; }
        public Nullable<long> UnitID { get; set; }
        public Nullable<long> PropertyID { get; set; }
        public string ProblemID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateOpened { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public Nullable<int> ReportedBy { get; set; }
        public string ContactPhone { get; set; }
        public string AssignedTo { get; set; }
        public string Resolution { get; set; }
        public Nullable<long> VendorID { get; set; }
    
        public virtual tbl_Tenant tbl_Tenant { get; set; }
        public virtual tbl_Vendor tbl_Vendor { get; set; }
        public virtual tbl_Properties tbl_Properties { get; set; }
    }
}
