//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShomaRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PropertyFloor
    {
        public long FloorID { get; set; }
        public Nullable<long> PID { get; set; }
        public string Coordinates { get; set; }
        public string FloorNo { get; set; }
        public string FloorPlan { get; set; }
    
        public virtual tbl_Properties tbl_Properties { get; set; }
    }
}
