//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShomaRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CashReceipts
    {
        public long CRID { get; set; }
        public Nullable<long> TenantID { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> PrePayment { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string CheckNumber { get; set; }
        public Nullable<long> PropertyID { get; set; }
        public Nullable<long> UnitID { get; set; }
        public Nullable<long> LeaseID { get; set; }
        public Nullable<int> Revision_Num { get; set; }
        public string PaymentType { get; set; }
        public Nullable<int> IsApplicant { get; set; }
        public Nullable<int> Status { get; set; }
        public string Description { get; set; }
        public string Batch { get; set; }
        public Nullable<int> UserID { get; set; }
        public string BankAccount { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public Nullable<System.DateTime> DepositAcctDate { get; set; }
    
        public virtual tbl_Lease tbl_Lease { get; set; }
        public virtual tbl_Login tbl_Login { get; set; }
        public virtual tbl_Properties tbl_Properties { get; set; }
        public virtual tbl_Properties tbl_Properties1 { get; set; }
        public virtual tbl_Tenant tbl_Tenant { get; set; }
    }
}
