//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShomaRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MoveInPayment
    {
        public long MIPayID { get; set; }
        public Nullable<long> TenantID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<decimal> MoveInCharges { get; set; }
        public Nullable<decimal> AdministrationFee { get; set; }
        public Nullable<decimal> VehicleRegistration { get; set; }
        public Nullable<decimal> SecurityDeposit { get; set; }
        public Nullable<decimal> PetFee { get; set; }
        public Nullable<decimal> Prorated_Rent { get; set; }
    }
}
