//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShomaRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ChargeType
    {
        public long CTID { get; set; }
        public string Charge_Type { get; set; }
        public string Summary_Charge_Type { get; set; }
        public string Charge_Description { get; set; }
        public string Charge_Reference { get; set; }
        public string Payment_Description { get; set; }
        public string Payment_Reference { get; set; }
        public string Revenue_Account { get; set; }
        public string Receivable_Account { get; set; }
        public string Prepayment_Account { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Time_Stamp { get; set; }
        public short Concession { get; set; }
    
        public virtual tbl_Login tbl_Login { get; set; }
    }
}
