//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShomaRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ApplicantHistory
    {
        public long AHID { get; set; }
        public Nullable<long> TenantID { get; set; }
        public string Country { get; set; }
        public string HomeAddress1 { get; set; }
        public string HomeAddress2 { get; set; }
        public Nullable<long> StateHome { get; set; }
        public string CityHome { get; set; }
        public string ZipHome { get; set; }
        public Nullable<int> RentOwn { get; set; }
        public Nullable<System.DateTime> MoveInDateFrom { get; set; }
        public Nullable<System.DateTime> MoveInDateTo { get; set; }
        public string MonthlyPayment { get; set; }
        public string Reason { get; set; }
        public string ApartmentCommunity { get; set; }
        public string ManagementCompany { get; set; }
        public string ManagementCompanyPhone { get; set; }
        public Nullable<int> IsProprNoticeLeaseAgreement { get; set; }
        public Nullable<long> ParentTOID { get; set; }
    }
}
