//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShomaRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MonthlyPayment
    {
        public long MPayID { get; set; }
        public Nullable<long> TenantID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<decimal> MonthlyCharges { get; set; }
        public Nullable<decimal> AdditionalParking { get; set; }
        public Nullable<decimal> StorageCharges { get; set; }
        public Nullable<decimal> PetRent { get; set; }
        public Nullable<decimal> TrashRecycle { get; set; }
        public Nullable<decimal> PestControl { get; set; }
        public Nullable<decimal> ConvergentBilling { get; set; }
        public Nullable<decimal> TotalMonthlyCharges { get; set; }
        public string Unit { get; set; }
        public string Model { get; set; }
        public string LeaseTerm { get; set; }
    }
}
