//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShomaRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TenantEventJoin
    {
        public long TEID { get; set; }
        public Nullable<long> TenantID { get; set; }
        public Nullable<long> EventID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<decimal> Fees { get; set; }
        public string Description { get; set; }
    
        public virtual tbl_TenantEventJoin tbl_TenantEventJoin1 { get; set; }
        public virtual tbl_TenantEventJoin tbl_TenantEventJoin2 { get; set; }
    }
}
