//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShomaRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CausingIssue
    {
        public long CausingIssueID { get; set; }
        public string CausingIssue { get; set; }
        public Nullable<long> ServiceIssueID { get; set; }
    }
}
