//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShomaRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PaymentAccounts
    {
        public long PAID { get; set; }
        public Nullable<long> TenantId { get; set; }
        public string NickName { get; set; }
        public string NameOnCard { get; set; }
        public string CardNumber { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public Nullable<int> CardType { get; set; }
        public Nullable<int> Default { get; set; }
        public Nullable<int> PayMethod { get; set; }
        public string BankName { get; set; }
        public string AccountName { get; set; }
        public string AccountNumber { get; set; }
        public string RoutingNumber { get; set; }
    }
}
