//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShomaRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Notice
    {
        public long NoticeID { get; set; }
        public Nullable<long> PID { get; set; }
        public Nullable<long> UID { get; set; }
        public Nullable<long> TID { get; set; }
        public Nullable<long> LeaseID { get; set; }
        public Nullable<int> Revision_Num { get; set; }
        public Nullable<System.DateTime> NoticeDate { get; set; }
        public Nullable<System.DateTime> IntendedMoveOut { get; set; }
        public string TerminationReason { get; set; }
        public Nullable<System.DateTime> CancelNoticeDate { get; set; }
    
        public virtual tbl_Tenant tbl_Tenant { get; set; }
        public virtual tbl_Lease tbl_Lease { get; set; }
        public virtual tbl_Properties tbl_Properties { get; set; }
    }
}
