//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShomaRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PropertyUnits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_PropertyUnits()
        {
            this.tbl_ApplyNow = new HashSet<tbl_ApplyNow>();
        }
    
        public long UID { get; set; }
        public Nullable<long> PID { get; set; }
        public string UnitNo { get; set; }
        public string Wing { get; set; }
        public string Building { get; set; }
        public Nullable<int> FloorNo { get; set; }
        public decimal Current_Rent { get; set; }
        public decimal Previous_Rent { get; set; }
        public decimal Market_Rent { get; set; }
        public decimal Deposit { get; set; }
        public string Leased { get; set; }
        public int Rooms { get; set; }
        public Nullable<int> Bedroom { get; set; }
        public Nullable<int> Bathroom { get; set; }
        public Nullable<int> Hall { get; set; }
        public int Den { get; set; }
        public int Furnished { get; set; }
        public int Fireplace { get; set; }
        public int Carpet { get; set; }
        public string Carpet_Color { get; set; }
        public string Wall_Paint_Color { get; set; }
        public int Drapes { get; set; }
        public int Air_Conditioning { get; set; }
        public int Range { get; set; }
        public int Gas_Range { get; set; }
        public int Elec_Range { get; set; }
        public int Washer_Hookup { get; set; }
        public int Dryer_Hookup { get; set; }
        public int Gas_Dryer_Hookup { get; set; }
        public int Elec_Dryer_Hookup { get; set; }
        public int Washer { get; set; }
        public int Dryer { get; set; }
        public int Refrigerator { get; set; }
        public int Dishwasher { get; set; }
        public int Disposal { get; set; }
        public string PetDetails { get; set; }
        public string Area { get; set; }
        public string FloorPlan { get; set; }
        public Nullable<System.DateTime> AvailableDate { get; set; }
        public int PendingMoveIn { get; set; }
        public Nullable<System.DateTime> IntendedMoveIn_Date { get; set; }
        public Nullable<System.DateTime> ActualMoveInDate { get; set; }
        public int PendingMoveOut { get; set; }
        public Nullable<System.DateTime> IntendMoveOutDate { get; set; }
        public Nullable<System.DateTime> ActualMoveOutDate { get; set; }
        public Nullable<System.DateTime> VacancyLoss_Date { get; set; }
        public Nullable<System.DateTime> OccupancyDate { get; set; }
        public string Coordinates { get; set; }
        public Nullable<int> Premium { get; set; }
        public string BalconyArea { get; set; }
        public string InteriorArea { get; set; }
        public string Notes { get; set; }
    
        public virtual tbl_Properties tbl_Properties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ApplyNow> tbl_ApplyNow { get; set; }
    }
}
