//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShomaRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BackgroundScreening
    {
        public int Id { get; set; }
        public int ApplyNowId { get; set; }
        public int ApplicantId { get; set; }
        public string ReportType { get; set; }
        public string SSN { get; set; }
        public string TransactionNumber { get; set; }
        public string ReportDate { get; set; }
        public string ApplicantDecision { get; set; }
        public string ApplicationDecision { get; set; }
        public string ApplicantScore { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
    }
}
