//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShomaRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Event()
        {
            this.tbl_EventBooking = new HashSet<tbl_EventBooking>();
        }
    
        public long EventID { get; set; }
        public string EventName { get; set; }
        public Nullable<long> PropertyID { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public string Photo { get; set; }
        public string Description { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public Nullable<System.DateTime> CreatedByDate { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.TimeSpan> EventTime { get; set; }
        public Nullable<decimal> Fees { get; set; }
    
        public virtual tbl_Login tbl_Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_EventBooking> tbl_EventBooking { get; set; }
        public virtual tbl_Properties tbl_Properties { get; set; }
    }
}
