//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShomaRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ZipCodes
    {
        public long City { get; set; }
        public long State { get; set; }
        public string Zip { get; set; }
        public string AreaCode { get; set; }
        public long ID { get; set; }
    
        public virtual tbl_City tbl_City { get; set; }
        public virtual tbl_State tbl_State { get; set; }
    }
}
