//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShomaRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LeaseTerms
    {
        public int LTID { get; set; }
        public Nullable<int> LeaseTerms { get; set; }
        public Nullable<bool> FormAgent { get; set; }
        public Nullable<int> OfferTerms { get; set; }
    }
}
