//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShomaRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AmenityPriceRange
    {
        public long ID { get; set; }
        public long AmenityID { get; set; }
        public string Duration { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<decimal> Fees { get; set; }
        public Nullable<long> DurationID { get; set; }
    }
}
